name: Frontend Code Quality

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # WICHTIG: SonarQube braucht die ganze Git-Historie

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Run Formatter
              run: npm run format-check

            - name: Run Linter
              run: npm run lint-check

            - name: Run Frontend Tests (Unit & Integration)
              run: npm run test

            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v2
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
              with:
                  args: >
                      -Dsonar.projectKey=speed-typer
                      -Dsonar.sources=.
